name: frontend
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  image_picker: ^0.8.6+2
  http: ^0.13.3
  google_sign_in: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  location: ^4.4.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.1.0
  mime: ^1.0.6
  dropdown_button2: ^2.3.9
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_svg: ^2.0.9
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/uploads/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 300

    - family: GmarketSansMedium
      fonts:
        - asset: assets/fonts/GmarketSansMedium.otf
          weight: 500

    - family: GmarketSansBold
      fonts:
        - asset: assets/fonts/GmarketSansBold.otf
          weight: 700
