name: project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile.png

    - assets/family.png
    - assets/fridge.png
    - assets/rightArrow.png

    - assets/upArrow.png
    - assets/downArrow.png
    - assets/star.png

    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
    - assets/img4.png

    - assets/heart.png
    - assets/comment.png

  fonts:
    - family: GmarketSansBold
      fonts:
        - asset: assets/GmarketSansTTFBold.ttf

    - family: GmarketSansMedium
      fonts:
        - asset: assets/GmarketSansTTFMedium.ttf

    - family: GmarketSansLight
      fonts:
        - asset: assets/GmarketSansTTFLight.ttf
